export const shapes = [
  // Basic 2D Shapes
  "Circle",
  "Square", 
  "Rectangle",
  "Triangle",
  "Oval/Ellipse",
  "Pentagon",
  "Hexagon",
  "Heptagon", 
  "Octagon",
  "Nonagon",
  "Decagon",
  "Rhombus",
  "Parallelogram",
  "Trapezoid",
  "Kite",
  "Diamond",

  // 2D Advanced Shapes
  "Star",
  "Heart",
  "Crescent",
  "Semicircle",
  "Quarter circle",
  "Sector",
  "Segment", 
  "Annulus",
  "Spiral",
  "Parabola",
  "Hyperbola",
  "Sine wave",
  "Zigzag",
  "Arrow",
  "Cross",
  "Plus sign",
  "Infinity symbol",
  "Teardrop",
  "Leaf shape",
  "Kidney shape",
  "Boomerang",

  // 3D Basic Shapes
  "Sphere",
  "Cube",
  "Rectangular prism",
  "Cylinder",
  "Cone",
  "Pyramid",
  "Triangular prism",
  "Hexagonal prism",
  "Torus",
  "Hemisphere",

  // 3D Advanced Shapes
  "Dodecahedron",
  "Icosahedron",
  "Tetrahedron",
  "Octahedron",
  "Pentagonal prism",
  "Truncated cone",
  "Ellipsoid",
  "Paraboloid",
  "Hyperboloid",
  "Mobius strip",
  "Klein bottle",
  "Geodesic dome",
  "Helix",

  // Irregular/Organic Shapes
  "Blob",
  "Amoeba shape",
  "Cloud shape",
  "Snowflake",
  "Lightning bolt",
  "Flame shape"
];